### ISSUE TITLE
Environment: Add travis for running test script

### ISSUE THREAD

**Issue by PabloAlice** [windingtree/wt-hotel-explorer#11]

**Comment by JirkaChadima** [comment]
Travis is already in place. We don't need to add it.

What is actually missing are any tests. If you make the tests working and add some of those, we'll make Travis run them for sure.

**Comment by JirkaChadima** [comment]
I don't really see any actual value in that. It would be much better to run the linter as a pre-push git hook if we want to keep the codebase clean. Until we actually have unit tests, I don't see a big added value in running the commits on Travis.

**Comment by PabloAlice** [comment]
using pre-push git hook I think you can't make sure that what you will merge actually has the linter approve. because we can't make sure that everyone is using the git hook, right?

**Comment by JirkaChadima** [comment]
After 9ca53ac builds are actually running. Closing this.
