### ISSUE TITLE
Wrong availability

### ISSUE THREAD

**Issue by czervenka** [windingtree/wt-hotel-explorer#137]
Availability is counted for days not for nights. When I select to stay from 13-14th of May, the web shows minimal availability from both days. It should display minimal availability for 13th of May only.

**Comment by JirkaChadima** [comment]
Fixed in https://github.com/windingtree/wt-pricing-algorithms/commit/4646be33a9cbfc1c62abb155e18b23c6711255cf

A fix will be deployed to playground and demo in a few minutes.
