### ISSUE TITLE
RoomType images carousel has a right padding

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-hotel-explorer#33]
I'm not sure if this is a bug or intentional behaviour, but I think the carousel should be really fullscreen without this padding.

![image](https://user-images.githubusercontent.com/375483/45610932-faf6c000-ba5d-11e8-952a-88f75bea595d.png)

**Comment by skkr** [comment]
You are right, it shouldn't be there. It's inherited from bootstrap's modals, but think is we can remove it for this full screen version.
