### ISSUE TITLE
Handle non-existent hotels (404 returned from API)

### ISSUE THREAD

**Issue by hynek-urban** [windingtree/wt-hotel-explorer#36]
On hotel detail page, HTTP 404 returned from read api is not handled well - the loader is spinning infinitely. Example:

https://hotel-explorer-demo.windingtree.com/hotels/0x4E8460C624688F06AD93da25758Ac58931FC961B

This is a case that can easily happen, for instance when a bookmarked hotel gets deleted from WT. Therefore, it should probably be handled somehow.

**Comment by JirkaChadima** [comment]
Thanks for the catch, error handling was not really implemented at all in the first phase...
