### ISSUE TITLE
Improve room availability design

### ISSUE THREAD

**Issue by skkr** [windingtree/wt-hotel-explorer#42]
The user-facing component is currently unstyled, all states can be observed on Hotel 0x04bdCB073f2e926EE4Bd5C6251623af5f498758d with one guest when the following dates are put in : 2018-08-26 and 2018-09-05.

https://github.com/windingtree/wt-hotel-explorer/pull/39

**Comment by JirkaChadima** [comment]
I think this issue was not necessary as all of that was handled in a PR. I think we can close this, now? Or are there any more plans on improving this detail?

**Comment by skkr** [comment]
Yes it was just more convenient to me to have it here, so all my pending tasks are here or in Asana. I'll close it.
