### ISSUE TITLE
Implement booking form

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-hotel-explorer#53]
# What is it?

After [defining a simple off-chain booking protocol](https://github.com/windingtree/wt-booking-api/blob/master/docs/swagger.yaml) and preparing an [example implementation of an API that can handle such requests](https://github.com/windingtree/wt-booking-api/), we want to show that the bookings are actually possible and that they can affect the availability.

# How is it supposed to work?

Every hotel will get another URI in its `dataIndex` file (called something like `bookingUri`and available within hotel data obtained from Read API) where it will tell the world where it expects all of the incoming bookings. The example implementation will take care of changing the availability appropriately after an incoming booking is accepted.

So the explorer should enable the users to fill a form with all of the data necessary for the booking and then send it to the given booking endpoint (if that exists for a hotel) with an appropriately computed price.

# Resources

- https://github.com/windingtree/wt-booking-api/blob/master/docs/swagger.yaml
- https://github.com/windingtree/wt-read-api/blob/develop/docs/swagger.yaml

**Comment by PabloAlice** [comment]
Will we have a wireframe for this? @skkr

**Comment by skkr** [comment]
@PabloAlice I asked Robin, he'll probably answer on Monday.

**Comment by menschikov** [comment]
@skkr please design a form like this for our library https://www.onetwotrip.com/en-gb/hotels/?referrer=aviasales&referrer_mrk=a1spdwtk9yps this is a good one from ux point of view, we don't need to create bicycle))

**Comment by menschikov** [comment]
This form is enough for search, less fields -> more attractive for users. All other filter fields will be shown after initial search
