### ISSUE TITLE
Hotels and room types without images look ugly

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-hotel-explorer#62]
We could probably use some placeholder to improve this situation. The same thing applies to room type listing on hotel detail.

![image](https://user-images.githubusercontent.com/375483/46790211-b4377580-cd3e-11e8-9a7b-03e034f46128.png)

**Comment by skkr** [comment]
Yes, we shouldn't hide the images but display a  placeholder image.

**Comment by JirkaChadima** [comment]
@skkr Do we have such placeholder somewhere? Or should we create one?

**Comment by menschikov** [comment]
![placeholder](https://user-images.githubusercontent.com/4557491/46849166-8833f700-ce07-11e8-8a0b-f396a3f8eb6c.png)
try for now

**Comment by skkr** [comment]
@JirkaChadima sorry for the late response!

@menschikov thanks for the image. I adjusted it a little so it looks better if is cropped (in room cards) and has a similar style to other cards.

![image](https://user-images.githubusercontent.com/1435069/46876877-d18b4300-ce15-11e8-9598-88e7fdb4bb22.png)

**Comment by JirkaChadima** [comment]
Thanks, fixed in #64
